---
# Create facts.d directory inside /etc/ansible and copy custom facts

- name: Create Ansible and facts.d and place custom facts
  hosts: mylaptop
  tasks:
          - name: Create ansible directory
            command: mkdir /etc/ansible
          - name: Create facts.d directory
            command: mkdir /etc/ansible/facts.d
          - name: Copy Custom Facts Files
            copy: src=getDate1.fact dest=/etc/ansible/facts.d mode=0755
          - name: Copy Custom Host file
            copy: src=getHostName.fact dest=/etc/ansible/facts.d mode=0755
...

# Here both getDate1.fact and getHostName.fact are copied to all the servers. The privileges need to be executable.
# Execute ansible mylaptop -m setup -a 'filter=ansible_local' to show all custom facts Refer output.png