---
# Create custom facts and execute them
# Before executing copy getdate1.fact to /root/ans-fact/getdate1.fact 
# Copy getdate2.fact to /etc/ansible/facts.d/getdate2.fact

- name: Create Custom Facts
  gather_facts: true

  # List of hosts will be affected
  hosts: oneserver


  # List of tasks
  tasks:
          - name: Create Facts Directory
            file:
              path: /root/facts.d
              recurse: yes
              state: directory

          - name: Copy getdate1 fact
            copy:
                     src: /root/ans-fact/getdate1.fact
                     dest: /root/facts.d
                     mode: 0755

          - name: Copy getdate2 fact
            copy:
                     src: /etc/ansible/facts.d/getdate2.fact
                     dest: /root/facts.d
                     mode: 0755

          - name: Reload Facts
            setup:
                     fact_path: /root/facts.d

          - name: Get Hostname
            debug:
                     msg: "{{ansible_hostname}}"

          - name: Get Custom Fact1
            debug:
                     msg: "{{ansible_local.getdate1}}"

          - name: Get Custom Fact2
            debug:
                     msg: "{{ansible_local.getdate2.date}}"

          - name: Get Custom Fact1 from hostvar
            debug:
                     msg: "{{ hostvars[ansible_hostname] }}"

          - name: Get Custom Fact2 from HostVar
            debug:
                     msg: "{{ hostvars[ansible_hostname] }}"

...