---
- name: Async Poll, fetch JOB IDs
  hosts: all
  vars:
          jobids: []

  tasks:
          - name: Sleep fe3c4c32ca96
            command: /bin/sleep 3
            async: 3
            poll: 1
            when: ansible_hostname == 'fe3c4c32ca96'
            register: result1

          - name: 9c2ce40376fa
            command: /bin/sleep 3
            async: 3
            poll: 1
            when: ansible_hostname == '9c2ce40376fa'
            register: result2

          - name: Sleep 258b709b0668
            command: /bin/sleep 3
            async: 3
            poll: 1
            when: ansible_hostname == '258b709b0668'
            register: result3

          - name: Sleep 0d184bedbd78
            command: /bin/sleep 3
            async: 3
            poll: 1
            when: ansible_hostname == '0d184bedbd78'
            register: result4

          - name: Fetch Job IDs
            set_fact:
                    jobids: >
                            {% if item.ansible_job_id is defined -%}
                              {{ jobids + [item.ansible_job_id] }}
                            {% else -%}
                              {{ jobids }}
                            {% endif %}
            with_items: "{{ [result1, result2, result3, result4] }}"

          - name: Print Job Ids
            debug:
                    var: jobids
...

# On executing the playbook, will show the list of job ids like in the output.
