---
- name: Sleep Nodes
  serial: 2 # On mentioning serial as 2, first all the 4 tasks will be executed for first 2 nodes and then 4 tasks will be executed for next 2 nodes.
  
# serial:
#   - 1
#   - 2
#   - 3 # in this case first all tasks will be run in 1 host, then 2 hosts and then 3 hosts

# serial:
#   - 16%
#   - 34%
#   - 50% # in this case first all tasks will be run in 16% of hosts, then 34% hosts and then 50% hosts
  
  hosts: all

  tasks:
          - name: Sleep 1
            command: /bin/sleep 5
          - name: Sleep 2
            command: /bin/sleep 5
          - name: Sleep 3
            command: /bin/sleep 5
          - name: Sleep 4
            command: /bin/sleep 5
...