---
# YAML documents begin with the document separator ---
# The minus in YAML this indicates a list item. The Playbook contains a list
# of plays, with each play being a dictionary

- name: 'create and access variables inside the playbook'

  # Target: where our play will run and options it will run with
  hosts: fe3c4c32ca96
  gather_facts: false

  # Variable: variables that will apply to the play, on all target systems
  vars:
          message:
                  remove: Removed Directory
                  create: Created Directory
          lists:
                  - blue
                  - black
                  - green
          anotherList:
                  [One, Two, Three]
  
  # Task: the list of tasks that will be executed within the playbook
  tasks:
          - name: List Variables
            debug:
                    msg: "{{lists}}"
          - name: List an Array
            debug:
                    msg: "{{lists[0]}}"
          - name: Remove and Create Directory
            debug:
                    msg: Removing and Creating Directory {{lists[1]}}
          - name: Remove Directory
            command: rm -rf {{lists[1]}}
          - name: Create Directory
            command: mkdir /root/{{lists[1]}}
          - name: Another List
            debug:
                    msg: Another List {{anotherList}}
          - name: Get Value
            debug:
                    msg: Another Value {{anotherList[2]}}
# Three dots indicate the end of a YAML document
...
