---
- name: Create Group, User & Copy a File
  hosts: dbserver, webservers
  tasks:
          - name: Create Group
            group: name=ansible state=present
          - name: Create User
            user: name=ansible group=ansible
          - name: Remove Existing Directory
            command: rm -rf /root/ansible-directory
          - name: Create Directory
            shell: mkdir /root/ansible-directory
          - name: Copy File
            copy: src=test.sh dest=/root/ansible-directory/ mode=0744
          - name: Execute File
            command: sh /root/ansible-directory/test.sh
...
