---
- name: Create Users using loop
  hosts: oneserver

  tasks:
          - name: Create User
            user:
                    name: "{{item}}"
            notify: My Handler
            with_items:
                    - one
                    - two
                    - three


  handlers:
          - name: My Handler
            debug:
                    msg: User Created
...
